# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d83d55d936bb0db595d24791be09f8cab5275be124ed3a5908335c77c17791ad71a759aa939044bc7db941cc0a912078c3a021788ee47dfaf469667c677cf1

test:
  secret_key_base: 4373b13a1712e4b57827b324f5046f72730c6e51fc308d7f9a595bc0c8b8b98b668bdc777cbff45f4d15895ad4c9ddc31f74df17ca463d4c726c959612e9ed89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
